//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

pub use super::{
    published_posts::Entity as PublishedPosts, user_licenses::Entity as UserLicenses,
    user_settings::Entity as UserSettings,
};
