//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

pub use super::published_posts::Entity as PublishedPosts;
pub use super::user_licenses::Entity as UserLicenses;
pub use super::user_settings::Entity as UserSettings;
