services:
    dev:
        image: dc-bot:latest
        platform: linux/amd64
        working_dir: /root/dev
        stdin_open: true
        tty: true
        restart: unless-stopped
        volumes:
            - .:/root/dev
            - ~/.ssh:/root/.ssh:ro
            - ~/.gitconfig:/root/.gitconfig:ro
            - cargo-target:/root/dev/target
        environment:
            - RUST_BACKTRACE=1
            - CARGO_INCREMENTAL=1
        # Keep container running for interactive shells
        command: sleep infinity

volumes:
    cargo-target:
