version: '3.8'

services:
    rust-dev:
        image: dc-bot-dev:latest
        platform: linux/amd64
        working_dir: /workspace
        stdin_open: true
        tty: true
        restart: unless-stopped
        volumes:
            - .:/workspace
            - ~/.ssh:/home/rustdev/.ssh:ro
            - ~/.gitconfig:/home/rustdev/.gitconfig:ro
            # Persistent cargo cache and registry for faster builds
            - rust-target:/workspace/target
            - rust-cargo-registry:/home/rustdev/.cargo/registry
            - rust-cargo-git:/home/rustdev/.cargo/git
        environment:
            - RUST_BACKTRACE=1
            - CARGO_INCREMENTAL=1
        # Keep container running for interactive shells
        command: sleep infinity

volumes:
    rust-target:
    rust-cargo-registry:
    rust-cargo-git:
