# Discord Bot Configuration Template
# 使用前请复制为 "config.toml" 并填入信息。

# [核心配置]
token = "YOUR_DISCORD_BOT_TOKEN_HERE"
time_offset = 7200
# [安全与权限]

# 拥有特殊权限的用户ID列表。
extra_admins_ids = [
    # 801430773600485407,239838081316945921
]
admin_role_ids = [

]


# 是否启用与备份Bot的同步功能
backup_enabled = false
# 备份Bot的接收端点 URL
endpoint = "http://127.0.0.1:8199"

# Gateway configuration for gRPC network integration
gateway_enabled = true # 是否启用 gRPC 网关集成
gateway_api_key = "your-gateway-api-key-here" # API 密钥
# gRPC 网关地址 - 支持多种格式：
# 1. 完整 URL: "https://grpc.example.com" 或 "http://localhost:50051"
# 2. 域名/IP: "grpc.example.com" (自动使用 HTTPS) 或 "localhost:50051" (自动使用 HTTP)
# 3. Cloudflare Tunnel: "your-tunnel.trycloudflare.com" (自动使用 HTTPS)
gateway_address = "grpc.example.com:443"