# Discord Bot  
# 使用前请复制为 "config.toml" 并填入信息。

# [核心配置]
token = "MTM4OTAxNjgyNzQ4NDU3MzgwOA.GALlNn.V-KPnum5rWOezUXj4X3i34NJiRAxX-5Hd7btNw"
time_offset = 7200
# [安全与权限]

# 拥有特殊权限的用户ID列表。
extra_admins_ids = [
    801430773600485407,239838081316945921
]
admin_role_ids = [

]


# 是否启用与备份Bot的同步功能
backup_enabled = false
# 备份Bot的接收端点 URL
endpoint = "http://127.0.0.1:8199"
